#Overfitting :
1.  model performs well on training data but does not perform well on the test data
2. model is memorizing the data instead of learning

In [1]:
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv ('fruit data.csv')
df

    fruit_label fruit_name     fruit_subtype  mass  width  height  color_score
0             1      apple      granny_smith   192    8.4     7.3         0.55
1             1      apple      granny_smith   180    8.0     6.8         0.59
2             1      apple      granny_smith   176    7.4     7.2         0.60
3             2   mandarin          mandarin    86    6.2     4.7         0.80
4             2   mandarin          mandarin    84    6.0     4.6         0.79
5             2   mandarin          mandarin    80    5.8     4.3         0.77
6             2   mandarin          mandarin    80    5.9     4.3         0.81
7             2   mandarin          mandarin    76    5.8     4.0         0.81
8             1      apple          braeburn   178    7.1     7.8         0.92
9             1      apple          braeburn   172    7.4     7.0         0.89
10            1      apple          braeburn   166    6.9     7.3         0.93
11            1      apple          braeburn   172    7.1     7.6         0.92
12            1      apple          braeburn   154    7.0     7.1         0.88
13            1      apple  golden_delicious   164    7.3     7.7         0.70
14            1      apple  golden_delicious   152    7.6     7.3         0.69
15            1      apple  golden_delicious   156    7.7     7.1         0.69
16            1      apple  golden_delicious   156    7.6     7.5         0.67
17            1      apple  golden_delicious   168    7.5     7.6         0.73
18            1      apple       cripps_pink   162    7.5     7.1         0.83
19            1      apple       cripps_pink   162    7.4     7.2         0.85
20            1      apple       cripps_pink   160    7.5     7.5         0.86
21            1      apple       cripps_pink   156    7.4     7.4         0.84
22            1      apple       cripps_pink   140    7.3     7.1         0.87
23            1      apple       cripps_pink   170    7.6     7.9         0.88
24            3     orange     spanish_jumbo   342    9.0     9.4         0.75
25            3     orange     spanish_jumbo   356    9.2     9.2         0.75
26            3     orange     spanish_jumbo   362    9.6     9.2         0.74
27            3     orange  selected_seconds   204    7.5     9.2         0.77
28            3     orange  selected_seconds   140    6.7     7.1         0.72
29            3     orange  selected_seconds   160    7.0     7.4         0.81
30            3     orange  selected_seconds   158    7.1     7.5         0.79
31            3     orange  selected_seconds   210    7.8     8.0         0.82
32            3     orange  selected_seconds   164    7.2     7.0         0.80
33            3     orange      turkey_navel   190    7.5     8.1         0.74
34            3     orange      turkey_navel   142    7.6     7.8         0.75
35            3     orange      turkey_navel   150    7.1     7.9         0.75
36            3     orange      turkey_navel   160    7.1     7.6         0.76
37            3     orange      turkey_navel   154    7.3     7.3         0.79
38            3     orange      turkey_navel   158    7.2     7.8         0.77
39            3     orange      turkey_navel   144    6.8     7.4         0.75
40            3     orange      turkey_navel   154    7.1     7.5         0.78
41            3     orange      turkey_navel   180    7.6     8.2         0.79
42            3     orange      turkey_navel   154    7.2     7.2         0.82
43            4      lemon    spanish_belsan   194    7.2    10.3         0.70
44            4      lemon    spanish_belsan   200    7.3    10.5         0.72
45            4      lemon    spanish_belsan   186    7.2     9.2         0.72
46            4      lemon    spanish_belsan   216    7.3    10.2         0.71
47            4      lemon    spanish_belsan   196    7.3     9.7         0.72
48            4      lemon    spanish_belsan   174    7.3    10.1         0.72
49            4      lemon           unknown   132    5.8     8.7         0.73
50            4      lemon           unknown   130    6.0     8.2         0.71
51            4      lemon           unknown   116    6.0     7.5         0.72
52            4      lemon           unknown   118    5.9     8.0         0.72
53            4      lemon           unknown   120    6.0     8.4         0.74
54            4      lemon           unknown   116    6.1     8.5         0.71
55            4      lemon           unknown   116    6.3     7.7         0.72
56            4      lemon           unknown   116    5.9     8.1         0.73
57            4      lemon           unknown   152    6.5     8.5         0.72
58            4      lemon           unknown   118    6.1     8.1         0.70

In [2]:
X = df.iloc[:, 3:6].values  
Y = df.iloc[:, 0].values
print(X)
print(Y)

[[192.    8.4   7.3]
 [180.    8.    6.8]
 [176.    7.4   7.2]
 [ 86.    6.2   4.7]
 [ 84.    6.    4.6]
 [ 80.    5.8   4.3]
 [ 80.    5.9   4.3]
 [ 76.    5.8   4. ]
 [178.    7.1   7.8]
 [172.    7.4   7. ]
 [166.    6.9   7.3]
 [172.    7.1   7.6]
 [154.    7.    7.1]
 [164.    7.3   7.7]
 [152.    7.6   7.3]
 [156.    7.7   7.1]
 [156.    7.6   7.5]
 [168.    7.5   7.6]
 [162.    7.5   7.1]
 [162.    7.4   7.2]
 [160.    7.5   7.5]
 [156.    7.4   7.4]
 [140.    7.3   7.1]
 [170.    7.6   7.9]
 [342.    9.    9.4]
 [356.    9.2   9.2]
 [362.    9.6   9.2]
 [204.    7.5   9.2]
 [140.    6.7   7.1]
 [160.    7.    7.4]
 [158.    7.1   7.5]
 [210.    7.8   8. ]
 [164.    7.2   7. ]
 [190.    7.5   8.1]
 [142.    7.6   7.8]
 [150.    7.1   7.9]
 [160.    7.1   7.6]
 [154.    7.3   7.3]
 [158.    7.2   7.8]
 [144.    6.8   7.4]
 [154.    7.1   7.5]
 [180.    7.6   8.2]
 [154.    7.2   7.2]
 [194.    7.2  10.3]
 [200.    7.3  10.5]
 [186.    7.2   9.2]
 [216.    7.3  10.2]
 [196.    7.3   9.7]
 [174.    7.3  10.1]
 [132.    5.8   8.7]
 [130.    6.    8.2]
 [116.    6.    7.5]
 [118.    5.9   8. ]
 [120.    6.    8.4]
 [116.    6.1   8.5]
 [116.    6.3   7.7]
 [116.    5.9   8.1]
 [152.    6.5   8.5]
 [118.    6.1   8.1]]
[1 1 1 2 2 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4]

In [3]:
from sklearn.model_selection import train_test_split
#from sklearn.cross_validation import train_test_split
X_train, X_test, Y_train , Y_test = train_test_split(X, Y, test_size=.20, random_state= 0)

In [4]:
print("splitting done")
print("X train records:", X_train.shape)
print("Y train records:", Y_train.shape)
print("X test records:", X_test.shape)
print("Y test records:", Y_test.shape)

splitting done
X train records: (47, 3)
Y train records: (47,)
X test records: (12, 3)
Y test records: (12,)

In [5]:
from sklearn import tree

clf_2 = tree.DecisionTreeClassifier(min_samples_split=2)

clf_2.fit(X_train, Y_train)

pred_2=clf_2.predict(X_test)

In [6]:
print (pred_2)

[3 3 4 1 1 1 1 4 3 1 2 3]

In [7]:
pred_train = clf_2.predict (X_train)
pred_train

array([3, 3, 3, 3, 4, 2, 1, 3, 4, 3, 3, 4, 1, 4, 3, 1, 2, 3, 1, 4, 1, 4,
       1, 1, 3, 1, 4, 4, 4, 3, 1, 1, 4, 3, 2, 1, 3, 1, 1, 1, 3, 4, 2, 1,
       4, 4, 4], dtype=int64)

In [8]:
#from sklearn.metrics import confusion_matrix, precision_score, recall_score , accuracy_score
from sklearn.metrics import accuracy_score
print("Accuracy score on test data: ", accuracy_score(Y_test, pred_2))
print("Accuracy score on training data: ", accuracy_score(Y_train, pred_train))

Accuracy score on test data:  0.75
Accuracy score on training data:  1.0

This is problem of Overfitting, We are getting 100% accuracy on training data 
but test data, we are getting 66% accuracy

In [9]:
df ['fruit_name'].value_counts()

fruit_name
apple       19
orange      19
lemon       16
mandarin     5
Name: count, dtype: int64

Underfitting
-Model performs poorly on the training data.

In [10]:
import warnings
warnings.filterwarnings("ignore")
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

df = pd.read_csv ('it salary.csv')
df

                        Positions  Level   Salary
0           IT Support Specialist      1    45000
1    Junior Systems Administrator      2    50000
2              Network Technician      3    60000
3       Junior Software Developer      4    80000
4                   Web Developer      5   110000
5           Network Administrator      6   150000
6                  System Analyst      7   200000
7               Software Engineer      8   300000
8              IT Project Manager      9   500000
9  Chief Technology Officer (CTO)     10  1000000